name: listviewbuilder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  video_player: ^2.9.2
    


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image.jpg
    - assets/videobck.mp4
    - assets/placeholder.jpg
    - assets/loading.jpg